services:
  flowers_front:
    build:
      context: ./flowers_front
      dockerfile: Dockerfile
    expose:
      - "5173"
    environment:
      - NODE_ENV=development

  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    expose:
      - "5174"
    environment:
      - NODE_ENV=development

  flowers_back:
    build:
      context: ./flowers_back
      dockerfile: Dockerfile
    expose:
      - "8000"


  # Aiogram bot service
  flowers_bot:
    build:
      context: ./flowers_bot
      dockerfile: Dockerfile
    expose:
      - "8001"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flowers_front
      - admin-panel
      - flowers_back
      - flowers_bot
    volumes:
      - ./logs/nginx:/var/log/nginx
