services:
  flowers_front:
    build:
      context: ./flowers_front
      dockerfile: Dockerfile
    expose:
      - "5173"
    environment:
      - NODE_ENV=development
    networks:
      - backend

  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    expose:
      - "5174"
    environment:
      - NODE_ENV=development
    networks:
      - backend

  flowers_back:
    build:
      context: ./flowers_back
      dockerfile: Dockerfile
    expose:
      - "8000"
#    ports:
#      - "8000:8000"
    volumes:
      - ./flowers_back/uploads:/app/uploads
      - ./flowers_back/categories:/app/categories
      - ./flowers_back/static:/app/static
    networks:
      - backend

  # Aiogram bot service
  flowers_bot:
    build:
      context: ./flowers_bot
      dockerfile: Dockerfile
    expose:
      - "8001"
    networks:
      - backend

  offer_backend:
    build:
      context: ./offer/offer_backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - backend

  offer_frontend:
    build:
      context: ./offer/offer_frontend
      dockerfile: Dockerfile
    expose:
      - "5175"
    networks:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flowers_front
      - admin-panel
      - flowers_back
      - flowers_bot
      - offer_frontend
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./flowers_back/uploads:/uploads
      - ./flowers_back/categories:/categories
      - ./flowers_back/static:/static
      - ./nginx/flourum.ru:/etc/letsencrypt/live/flourum.ru
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge
