"""empty message

Revision ID: 0bda85e404e1
Revises: 67b70a2464c0
Create Date: 2025-04-19 12:21:44.847950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bda85e404e1'
down_revision: Union[str, None] = '67b70a2464c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.alter_column('categories', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
