"""empty message

Revision ID: 0be92e2ad0c7
Revises: 6c620b59dc25
Create Date: 2025-03-07 05:10:54.439076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be92e2ad0c7'
down_revision: Union[str, None] = '6c620b59dc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pays', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pays', 'email')
    # ### end Alembic commands ###
