"""empty message

Revision ID: 205579c258bb
Revises: bceaa50fd66e
Create Date: 2025-04-21 11:14:59.379490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '205579c258bb'
down_revision: Union[str, None] = 'bceaa50fd66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = inspector.get_columns('products')
    if 'photos' not in [col['name'] for col in columns]:
        op.add_column('products', sa.Column('photos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'photos')
    # ### end Alembic commands ###
