"""empty message

Revision ID: 29d24b3d2ec9
Revises: 4bfc64afa216
Create Date: 2025-02-28 13:06:06.756009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d24b3d2ec9'
down_revision: Union[str, None] = '4bfc64afa216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pays', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('pays', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('pays', sa.Column('status', sa.String(), nullable=True))
    op.add_column('pays', sa.Column('last_pay_date', sa.DateTime(), nullable=True))
    op.add_column('pays', sa.Column('paid_until', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'pays', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pays', type_='foreignkey')
    op.drop_column('pays', 'paid_until')
    op.drop_column('pays', 'last_pay_date')
    op.drop_column('pays', 'status')
    op.drop_column('pays', 'user_id')
    op.drop_column('pays', 'id')
    # ### end Alembic commands ###
