"""Add is_sent field to orders

Revision ID: 327cb1a2a644
Revises: 572d2e5e828c
Create Date: 2025-01-04 18:46:59.368981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327cb1a2a644'
down_revision: Union[str, None] = '572d2e5e828c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultations')
    op.add_column('orders', sa.Column('status', sa.Enum('NOT_PAID', 'PAID', 'CANCELED', name='orderstatus'), nullable=True))
    op.add_column('orders', sa.Column('is_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'is_sent')
    op.drop_column('orders', 'status')
    op.create_table('consultations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='consultations_pkey')
    )
    # ### end Alembic commands ###
