"""empty message

Revision ID: 37163bf6da52
Revises: 9a30973e61d5
Create Date: 2025-04-27 16:19:10.084578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37163bf6da52'
down_revision: Union[str, None] = '9a30973e61d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_delivery_cost', sa.Column('is_yandex_geo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_delivery_cost', 'is_yandex_geo')
    # ### end Alembic commands ###
