"""empty message

Revision ID: 52abe32e4f2a
Revises: 39aa37e8a82b
Create Date: 2025-04-23 20:44:52.180771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52abe32e4f2a'
down_revision: Union[str, None] = '205579c258bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_value_key', 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categories_value_key', 'categories', ['value'])
    # ### end Alembic commands ###
