"""empty message

Revision ID: 6c620b59dc25
Revises: 29d24b3d2ec9
Create Date: 2025-02-28 13:35:39.711718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c620b59dc25'
down_revision: Union[str, None] = '29d24b3d2ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pays', sa.Column('payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pays', 'payment_id')
    # ### end Alembic commands ###
