"""orders

Revision ID: 6fe768ddb1c4
Revises: e0b9d692bbbb
Create Date: 2025-01-04 18:26:45.593829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe768ddb1c4'
down_revision: Union[str, None] = 'e0b9d692bbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultations')
    op.add_column('order_items', sa.Column('name', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('price', sa.Float(), nullable=False))
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.alter_column('orders', 'delivery_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'is_self_pickup',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.drop_column('orders', 'is_paid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.alter_column('orders', 'is_self_pickup',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('orders', 'delivery_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'price')
    op.drop_column('order_items', 'name')
    op.create_table('consultations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='consultations_pkey')
    )
    # ### end Alembic commands ###
