"""empty message

Revision ID: 7e1b870ab46a
Revises: e31c2cedcffa
Create Date: 2025-04-18 11:26:12.175446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1b870ab46a'
down_revision: Union[str, None] = 'e31c2cedcffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photos', sa.JSON(), nullable=True))
    op.alter_column('products', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'photos')
    # ### end Alembic commands ###
