"""empty message

Revision ID: 9a30973e61d5
Revises: 52abe32e4f2a
Create Date: 2025-04-27 15:46:53.718729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a30973e61d5'
down_revision: Union[str, None] = '52abe32e4f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_value_key', 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categories_value_key', 'categories', ['value'])
    # ### end Alembic commands ###
