"""empty message

Revision ID: 9ae5a6f63a2f
Revises: 0be92e2ad0c7
Create Date: 2025-03-11 22:46:05.938155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae5a6f63a2f'
down_revision: Union[str, None] = '0be92e2ad0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pays', sa.Column('rebill_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pays', 'rebill_id')
    # ### end Alembic commands ###
