"""shop

Revision ID: b29a88c03003
Revises: 34619a3c6654
Create Date: 2025-02-21 20:17:51.007915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29a88c03003'
down_revision: Union[str, None] = '34619a3c6654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('inn', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'phone')
    op.drop_column('shops', 'inn')
    # ### end Alembic commands ###
