"""empty message

Revision ID: b8cf6ca8aaf8
Revises: effedbbebe36
Create Date: 2025-03-16 15:53:29.556716

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.models.product import ProductAvailabilityVariants

# revision identifiers, used by Alembic.
revision: str = 'b8cf6ca8aaf8'
down_revision: Union[str, None] = 'effedbbebe36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products',
        sa.Column('availability',
                  sa.String(),
                  nullable=False,
                  server_default=ProductAvailabilityVariants.AVAILABLE.value  # Значение по умолчанию
                  ), )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'availability')
    # ### end Alembic commands ###
