"""empty message

Revision ID: bceaa50fd66e
Revises: 8c188775dc35
Create Date: 2025-04-21 11:07:50.532334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bceaa50fd66e'
down_revision: Union[str, None] = '8c188775dc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('whatsapp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'whatsapp')
    # ### end Alembic commands ###
