"""empty message

Revision ID: c83091072288
Revises: 52abe32e4f2a
Create Date: 2025-04-28 03:30:00.003087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision: str = 'c83091072288'
down_revision: Union[str, None] = '52abe32e4f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    columns = [col['name'] for col in inspector.get_columns('shop_delivery_cost')]
    if 'is_yandex_geo' not in columns:
        op.add_column('shop_delivery_cost', sa.Column('is_yandex_geo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_delivery_cost', 'is_yandex_geo')
    # ### end Alembic commands ###
