"""empty message

Revision ID: d12c59132d59
Revises: 7e1b870ab46a
Create Date: 2025-04-18 12:27:04.887344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision: str = 'd12c59132d59'
down_revision: Union[str, None] = '7e1b870ab46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = reflection.Inspector.from_engine(conn)
    columns = [col["name"] for col in inspector.get_columns("categories")]
    if "value" not in columns:
        op.add_column('categories', sa.Column('value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'value')
    # ### end Alembic commands ###
