"""empty message

Revision ID: effedbbebe36
Revises: 9ae5a6f63a2f
Create Date: 2025-03-13 02:14:52.032834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effedbbebe36'
down_revision: Union[str, None] = '9ae5a6f63a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pays', sa.Column('pan', sa.String(), nullable=True))
    op.add_column('pays', sa.Column('card_id', sa.String(), nullable=True))
    op.add_column('pays', sa.Column('order_id', sa.String(), nullable=True))
    op.add_column('pays', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pays', 'timestamp')
    op.drop_column('pays', 'order_id')
    op.drop_column('pays', 'card_id')
    op.drop_column('pays', 'pan')
    # ### end Alembic commands ###
